name: Setup Monitoring Stack (Prometheus + Grafana)

on:
  workflow_dispatch:

jobs:
  deploy-monitoring:
    name: Install Prometheus & Grafana on EC2
    runs-on: ubuntu-latest

    steps:
      - name: Connect to EC2 and set up monitoring stack
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Update system
            sudo apt update -y

            # Install Docker if not already installed
            if ! command -v docker &> /dev/null; then
              curl -fsSL https://get.docker.com | sudo bash
              sudo usermod -aG docker $USER
            fi

            # Create Docker Compose file
            mkdir -p ~/monitoring
            cd ~/monitoring

            cat > docker-compose.yml <<EOF
            version: '3'

            services:
              prometheus:
                image: prom/prometheus
                ports:
                  - "9090:9090"
                volumes:
                  - ./prometheus.yml:/etc/prometheus/prometheus.yml

              node-exporter:
                image: prom/node-exporter
                ports:
                  - "9100:9100"

              grafana:
                image: grafana/grafana
                ports:
                  - "3001:3000"
                environment:
                  - GF_SECURITY_ADMIN_USER=admin
                  - GF_SECURITY_ADMIN_PASSWORD=admin
                volumes:
                  - grafana-data:/var/lib/grafana

            volumes:
              grafana-data:
            EOF

            # Create Prometheus config
            cat > prometheus.yml <<EOF
            global:
              scrape_interval: 15s

            scrape_configs:
              - job_name: 'prometheus'
                static_configs:
                  - targets: ['localhost:9090']

              - job_name: 'node-exporter'
                static_configs:
                  - targets: ['localhost:9100']
            EOF

            # Start stack
            docker compose down
            docker compose up -d
